### PR TITLE
Auto merge dependabot dev dependency PRs

### PR DESCRIPTION
**Pull request by notlee**

### CODE REVIEW

**Comment by notlee** [comment]
hey @Financial-Times/ads, we're auto-merging dev dependencies which are bumped by dependabot in working hours if tests pass: https://github.com/Financial-Times/origami/issues/55

I opened a PR on all Origami things, including those maintained by other teams. Feel free to close this PR if you wouldn't like this for some reason!

**Comment by carlesandres** [comment]
It's really nice functionality and, considering it's only dev dependencies, it should be safe. What do you think @andrewgeorgiou1981 ?

**Comment by notlee** [comment]
We just noticed that Dependabot can't auto merge without its PR being approved. I have another PR on the way to have an Origami bot auto approve Dependabot so these can be merged :)

**Comment by notlee** [comment]
🤖 🤝 🤖

**Pull request merged**
